// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core';

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    SvgIcon: typeof import('./src/components/SvgIcon/SvgIcon.vue')['default'];
    VanButton: typeof import('vant/es')['Button'];
    VanCellGroup: typeof import('vant/es')['CellGroup'];
    VanConfigProvider: typeof import('vant/es')['ConfigProvider'];
    VanField: typeof import('vant/es')['Field'];
    VanForm: typeof import('vant/es')['Form'];
    VanTab: typeof import('vant/es')['Tab'];
    VanTabs: typeof import('vant/es')['Tabs'];
  }
}

export {};
